name: flutterish_pdf_viewer
description: A PDF viewer in Flutter that does not require any external native dependencies
version: 0.1.0
homepage: https://github.com/evaisse/flutterish_pdf_viewer

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  path_provider: ^2.1.0
  pdf: ^3.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
